### ISSUE TITLE
To test the trained model

### ISSUE THREAD

**Issue by genius015** [KumarLabJax/MouseTracking#2]
Dear KumarLab,

First of all, thank you for sharing your valuable research materials. I found your research a month ago, thanks to your kind code description, I could follow your work more easily. 

At this moment, I have one question about your description.
The question is how can I test some images based on the trained model. 
For example, after I trained KOMP_Dataset based on your instruction(modified number of steps), I obtained three files denoted as model.ckpt-1000(index, meta, data respectively). Now I want to test some images or videos, but, I cannot find video data on your website except for your inference code. 
Is it possible to test some images from OFA_Dataset? If it is possible, could you let me know how to do it?
If not, could you share your video data?

Thank you for your help.

**Comment by SkepticRaven** [comment]
We're not currently sharing any raw videos. We do, however, share the training/validation/test datasets.
The inference code will not operate on images directly, but we can convert the annotated images into a video for testing.

Extracting and using the test KOMP dataset could go as follows:
Download the test dataset: `wget ftp://ftp.jax.org/kumarlab/2019_Tracking/TestGT_Dataset.tar` (or download through [this link](https://www.kumarlab.org/2019/02/12/single-mouse-tracking-annotated-dataset/))
Extract the data: `tar -xvf TestGT_Dataset.tar`
Convert the KOMP2 frames into a video: `ffmpeg -r 1 -i Ref/KOMP2_%d.png -c:v mpeg4 -q 0 KOMP2_TestDataset.avi`

This will re-produce the 1fps video that we have annotated in the test dataset. Additionally, you can change the prefix to be one of the other test datasets we've annotated (Black, Albino, Piebald, Gray, 24Hr, KOMP2).
You can also convert the validation dataset to a video as well using a similar approach. Since the training/validation sets are randomly sampled, the video may be difficult to watch due to the arena shifting around between setups.

To then run the model on the video and see the results, the command would look something like this:
`python main.py --net_type segellreg Infer --model construct_segellreg_v8 --network_to_restoremodel.ckpt-1000 --input_movie KOMP2_TestDataset.avi --ellfit_movie_output --ellfit_output`

**Comment by genius015** [comment]
Thank you for your detailed instruction. 

By following your advice, I could get two files (.avi and .npz files).
Thank you again.
